name: mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dio: ^5.3.3
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.5
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_markdown: ^0.6.18+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/aysecaglayan.png


