FROM amazoncorretto:17-alpine3.15 AS TEMP_BUILD_IMAGE
ENV APP_HOME=/game-lounge-backend/
WORKDIR $APP_HOME
COPY . $APP_HOME
COPY build.gradle.kts settings.gradle.kts gradlew $APP_HOME
COPY gradle $APP_HOME/gradle
RUN ./gradlew build -x test || return 0 
COPY . .
RUN ./gradlew build -x test

FROM amazoncorretto:17-alpine3.15
ENV ARTIFACT_NAME=backend-0.0.1-SNAPSHOT.jar
ENV APP_HOME=/game-lounge-backend/
WORKDIR $APP_HOME
EXPOSE 8080
RUN mkdir /backend
COPY --from=TEMP_BUILD_IMAGE $APP_HOME/build/libs/$ARTIFACT_NAME ./spring-boot-application.jar
ENTRYPOINT ["java", "-jar", "spring-boot-application.jar"]