name: Frontend Docker Build

on:
  workflow_dispatch:
  # push:
  #   branches: [ develop ]
  #   paths: 
  #     - 'app/frontend/**'

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    env:
      working-directory: ./app/frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: ${{env.working-directory}}
      run: |
        docker build -t erkamkavak/gamelounge-frontend:${{ github.run_number }} .

    - name: Login to Docker Hub
      run: echo "gameLounge2019" | docker login -u "erkamkavak" --password-stdin

    - name: Push Docker image
      run: |
        docker push erkamkavak/gamelounge-frontend:${{ github.run_number }}